FOSSUChennai/Communities

package-lock.json, package.json, src/app/events.tsx, src/app/hero.tsx, src/app/nav.tsx, src/data/events.json
=> design draft 1 is complete

src/app/events.tsx, src/components/EmptyEventCard.tsx, src/data/events.json, tsconfig.json
Empty State Handler
Added Community Logo to the card
Hover State
Normal State
=> Created Empty State handler cards for both events

src/app/calltoaction.tsx
Solving the Issue #16 
Updated the link for the button Contribute to open Contributing.md file of the repo.
=> Changed contribute link to Contributing.md

src/data/events.json
Join us for IN PERSON Grafana labs x Presidio meetup on Jan 25th from 9:30 am, hosted by Presidio in Chennai!
=> Add: Grafana event on  Jan 25

src/app/events.tsx, src/data/events.json
Description: "Resolves #25 - Changed date format from YYYY-MM-DD to DD-MM-YYYY to match Indian standard"
=> Fix: Update date format to Indian standard (DD-MM-YYYY)

src/app/events.tsx
Old PR was accidentally closed
Fixes(#28)
Added dynamically sizing card based on longest event title, along with badge and locations being positioned properly
> Preview
=> Added longest title based card height

src/components/pages/home/events.tsx
Fixes issue : #21 
Fixed the community name and logo alignment and added tool tip of better UX
=> fix(community): update title-logo alignment

src/components/github-button.tsx
=> fix(github-button): update star count state and improve button display

src/data/events.json
Fixed #68
Added Community Event
=> feat(events): add OWASP Meetup event details to events.json

next.config.ts, src/data/events.json
=> Add: KCD Chennai 2025

README.md
Description: Update the Readme with contributing points so that people can quickly glance and create PRs with the suggested guidelines
=> docs(readme): added few pointers for contributing

README.md
Description: Added an Image of Contributors who are the heros of the repo.
=> docs(readme): added contributors to appreciate the heros

src/components/pages/home/events.tsx
Here I validate the Spaces and the Proper Capital case Handling
=>  incorrect capitalization for place names (#79) on 08-01-2025

src/components/pages/home/events.tsx
This PR resolves the Issue #88 by enhancing the event cards display order by:
- Sorting the events data by dates in ascending order
**events.tsx**: Added a sort functionality to sort the events in ascending order to the variables 'monthlyEvents; and 'upcomingEvents' which has the events data that is displayed on the UI.
The following screenshots show the changes after implementing the sorting functionality.
Before:
After:
=> fix: added sort function to sort events in ascending order

next.config.ts, src/data/events.json
Welcome to build2learn - Where Innovation Meets Community! Imagine a hackathon, but with a twist!🤔 It's not just about building incredible micro products; it's about forging lifelong connections with like-minded individuals who share your passion for innovation! 🤝💡At build2learn, we believe that magic happens when engineers come together to do what they love - BUILD!",
Are you someone with a side project that you've been dreaming of bringing to life?
build2learn is your chance to turn that dream into reality! ⏰🌟
Are you a student eager to create something extraordinary but in need of mentors to guide you?
build2learn is the launchpad you've been waiting for! 🎓🚀
Or maybe you're someone who thrives on helping others unleash their full potential? build2learn is the perfect platform to make a …
=> Add: build2learn on 2025-01-25

src/data/events.json
Microsoft Azure Skillup Tamilnadu Session 2 by Azure Developer Community Tamilnadu
=> Add: Microsoft Azure Skillup Tamilnadu Session 2 on 2025-02-15

src/data/events.json
Reference link: https://fossunited.org/c/chennai/2025/Jan
=> FOSS United Chennai jan meetup added

src/data/events.json
=> Merged conflicts and added ChennaiPy

src/data/events.json
Cloud Native Chennai - Jan 2025 Meetup on 2025-01-25 at Tekclan Software Solutions PVT. LTD
closes #101
=> Add: Cloud Native Chennai - Jan 2025 Meetup

src/data/events.json
Hi @JustinBenito 
Thanks for the immediate response.
Resolved issue #109
=> Updated the eventlink

src/data/events.json
Added a new event "Hackers Thiruvizha" to be held on 08/02/2025
=> Add: hackersthiruvizha 

next.config.ts, src/data/events.json
=> Feat: Chennai React Anniversary Mega Meetup on March 1, 2025

src/components/pages/home/events.tsx, src/data/events.json
=> Feat(TAI): add TAI Connect event and UI cosmetic fixes

src/data/events.json
Added KCD Chennai Konnekt event to the events.json
https://www.linkedin.com/posts/kcdchennai_kubernetes-kcdchennai2025-activity-7292127182477238272-6sem?utm_source=share&utm_medium=member_desktop&rcm=ACoAAEAs5A4BLLUxijBSrzUtVOtGe7ch4BlggHM
=> Add KCD Chennai Konnekt to events

src/components/pages/home/events.tsx
=> bugfix : Current date issue fix

src/components/no-events-card.tsx
Removed extra styling for a cleaner look.
Made the CalendarX icon thinner for a sleek design.
=>  Cleaned Up Empty Event Card Styling

src/data/events.json
24th Build2Learn session added
=> 24th build2learn event added

package.json, src/components/pages/home/community.tsx
=> [ Demo ] - Community Pages 

next.config.ts
=> Update next.config.ts - secure.meetupstatic.com

src/data/events.json
We’re thrilled to announce the Grafana and Friends Chennai Community Event happening this March 8, 2025, in the afternoon!
=> Add: Grafana Meetup on March 8

src/data/events.json
We're excited to invite you to the first Platform Engineering Meetup in Coimbatore!
=> Platform Engineering Coimbatore Meetup March 2025

src/data/events.json
We’re thrilled to announce that the FOSS United Chennai Community Event is on March 22, 2025.
=> Add: FOSS Meetup Chennai on 22-03-2025

package-lock.json, package.json, src/components/pages/home/hero.tsx
Added motion graphics to the Hero section to create a more dynamic and engaging experience. The subtle animations enhance UX by drawing attention to key elements, making the section feel more interactive and visually appealing compared to a static design 🚀✨
=> Updated Hero section with motion graphics 

src/data/events.json
Vanakkam Makkalae!
We are back with a Banger
​FFDG Chennai is here
to help you build cool apps.
​tbh, you don't need to know anything.
Just your good vibes to turn ideas into reality.
​Come join us at
🗓️ 22nd March, 2025
⏰ 9:00 AM - 1:00 PM
📍 St. Joseph's Institute of Technology, Hope Room, Ground Floor, Admin Block
​See you there, makkale! 💜
=> Add: FFDG Chennai meetup on 22.03.2025

src/data/events.json
This PR corrects a typo in the location details of the **FOSS Meetup Chennai** `events.json` file to ensure accurate event information.
- Fixed the typo in the location name.
Accurate event details are crucial to prevent confusion and provide the correct venue information.
Let me know if any further adjustments are needed! 🚀
=> fix: Updated location in the FOSS Meetup Chennai

src/data/events.json
=> feat: added IWD event

src/data/events.json
Updated ChennaiReactmeetup event details with revised location in events.json.
=> feat: add ChennaiReactmeetup event with updated location

src/components/pages/Communities/Community.tsx
This PR addresses a small UI issue in the Community section where Eslint errors. The issue was caused by unused of parameters in the code.
- Made sure to use all lines of the code.
- No breaking changes.
- Ready for review.
=> Fix Community Section 

src/data/events.json
🚀[MongoDB User Group Chennai](https://www.linkedin.com/company/mugchennai/) - 𝗔𝗽𝗿𝗶𝗹 𝗠𝗲𝗲𝘁𝘂𝗽: 𝗧𝗵𝗲 𝗔𝗜 𝗔𝘄𝗮𝗸𝗲𝗻𝘀! 🤖✨
Join us for an exciting in-person meetup where we explore the power of AI and [MongoDB](https://www.linkedin.com/company/mongodbinc/)! Whether you're a developer, data enthusiast, or just curious about the intersection of AI and databases, this is the perfect place to learn, network, and grow.
📅 𝗗𝗮𝘁𝗲: Saturday, April 19
⏰ 𝗧𝗶𝗺𝗲: 9:30 AM - 1:00 PM (GMT+5:50)
📍 𝗩𝗲𝗻𝘂𝗲: [IBM](https://www.linkedin.com/company/ibm/), 5th Floor, Unit 3, Pinnacle Building, Ascendas IT Park, CSIR Road, Tharamani, Chennai - 600113
🎟️𝗥𝗲𝗴𝗶𝘀𝘁𝗿𝗮𝘁𝗶𝗼𝗻: https://lnkd.in/gXBWtR-b
🔥 𝗪𝗵𝘆 𝘆𝗼𝘂 𝘀𝗵𝗼𝘂𝗹𝗱 𝗮𝘁𝘁𝗲𝗻𝗱?
✅ Learn how AI is transforming the database landscape
✅ Engage with industry experts and MongoDB professionals
✅ …
=> feat: add MUG April Meetup on 19th April

src/data/events.json
Hi, KCD Chennai recently changed the event location, So this commit is to change the existing location to new location, and also I modified the website url to point it out to new one.
=> fix: correct event location and website for kcd chennai 2025

src/components/pages/Communities/Community.tsx, src/components/pages/home/calltoaction.tsx
- Aligned the Rocket Image in the Call to Action Component 
- Added Gradient Border Effects to Community Page Card
- Fixed Some Spacing Inconsistencies
This PR fixes the issue #208 and #206
=> Fixed Issue #208 and Issue #206 

src/components/pages/Communities/Community.tsx
- I have fixed the height problem in cards.
- now they will be in same sizes in thier respective rows.
- the line seperating the description and links has been reworked, and will not appear if there is no link provided.
- and i replaced the margins in percentage so that the margin changes with display sizes.
- added shadow to the container.
> _Image 1 Showing the UI fix in cards_
---
> _Image 2 Showing the margins replaced in percents_
=> Fixed Issue #207 and improved UI

src/data/events.json
🚀 Secure Your Spot: AI & Data Science Collective 
Join us for an exclusive AI & Data Science Collective, where developers, researchers, and AI enthusiasts unite to explore groundbreaking innovations in Artificial Intelligence and Data Science!
This in-person gathering is designed to foster learning, collaboration, and networking among the brightest minds in AI. Whether you're a developer, data scientist, startup founder, or AI enthusiast, this event is your gateway to discovering the latest trends, tools, and breakthroughs in the field.
🎯 What’s in Store?
🔍 Expert Talks – Gain insights from AI & Data Science leaders
🛠️ Live Demos & Workshops – Hands-on sessions with the latest AI frameworks and FireDucks.
🤝 Networking & Collaboration – Connect with developers, researchers, and industry …
=> feat: Add DevRelSquad meetup on 26th April

src/data/communities.json
This pull request adds the FFDG Chennai community to the open-source project.
Changes Made:
A detailed description of the FFDG Chennai community was added, highlighting its focus on innovation, collaboration, and low-code development.
Enhanced the community introduction to be more welcoming and inclusive.
It will help foster cross-community collaboration, enabling members to leverage diverse skill sets and share innovative ideas.
By bringing together enthusiasts from different technical backgrounds, it will strengthen the open-source ecosystem.
Why These Changes?
Integrating FFDG Chennai will help create better visibility for community-driven projects and encourage collaboration among developers, engineers, and innovators from diverse groups.
=> Feat: Integrating FFDG Chennai Community 

next.config.ts, src/data/events.json
Startup Atti is a communities & fellow startups driven initiative designed to bring startups and like-minded individuals together for meaningful offline networking.
Link: https://linktr.ee/startupatti
=> feat: Add Startup Atti Event on 26 april 2025

src/data/events.json
- Added the Elastic Chennai User Group Event to the site
=> feat: added elastic chennai meetup

src/data/events.json
Updating the address due to recent venue changes
=> feat: updated MongoDB Event address

src/data/events.json
Join the TechNexus Community for an exciting day of discussions, learning, and networking at Microsoft Developer Day! This event will bring together Microsoft MVPs and industry experts to share insights, trends, and experiences in the ever-evolving world of AI and software development. Discover the latest advancements, learn from real-world implementations, and connect with fellow developers who are shaping the future of technology.
=> feat: add Microsoft Developer Day

package-lock.json, package.json, src/app/rss/route.ts, src/components/shared/header.tsx, src/types/jsonfeed-to-rss.d.ts
=> feat: add RSS feed generation for upcoming events

src/data/events.json
Added Swift Chennai Chapter #01 event
=> Added Swift Chennai Chapter #01 event

src/components/pages/home/events.tsx
=> feat(time): displays time of the event

src/components/pages/home/hero.tsx, src/data/communities.json
Added CTOtalk community in the communities.json
=> feat: add ctotalk community

src/data/events.json
Added D3 Community Meetup #1 on 2025-05-03
=> feat: add D3 Community Meetup #1 on 2025-05-03

src/data/events.json
Added an upcoming event for Build2Learn. It is happening on May 17.
=> feat: added an upcoming event for Build2Learn

src/data/communities.json
Added the social media links for JSLovers community
=> feat: added social media links

public/sitemap.xml
Added the /Communities and /rss endpoints to the sitemap.xml
**Related Issue**
Closes #271
=> feat(sitemap): added /Communities and /rss endpoints

src/data/events.json
* Added a new event to the events list.
* Included all required fields in the event JSON.
* Verified date, time, and logo formatting.
* Please double-check the event link and logo URL before merging from your side once
=> feat(events): added Code on JVM Chennai - May Meetup event

src/data/events.json
Added D3 Community Meetup 2 on 2025-06-21
=> feat: add D3 Community Meetup #2 on 2025-06-21

src/components/pages/home/events.tsx
=> feat: no need for manual deployment, just a merge to the main repo is good 

.github/workflows/json-validation.yml
This pull request introduces a GitHub Actions workflow to validate and automate JSON file updates for `events.json` and `communities.json`. The workflow ensures proper JSON syntax, provides feedback on pull requests, and automates merging if all conditions are met. Below are the key changes:
* **Workflow Setup**: Added a new workflow in `.github/workflows/json-validation.yml` to validate JSON syntax for `src/data/events.json` and `src/data/communities.json` on pull requests.
* **Linting Steps**:
- Added steps to lint `events.json` and `communities.json` using `jsonlint`, with outputs indicating success or failure.
- Added conditional steps to comment on pull requests with detailed results for both success and failure scenarios.
* **Approval and Auto-Merge**:
- Automatically approves the …
=> [Feat] : Verification of JSON, Auto Approval and Merging + Cleanup

.github/workflows/json-validation.yml
This pull request updates the workflow in `.github/workflows/json-validation.yml` to handle pull requests originating from forks more effectively. The changes ensure that branches from forked repositories are not deleted after a successful merge.
Key changes related to fork handling:
* Added a new variable `isFork` to determine whether the pull request originates from a forked repository.
* Implemented logic to check if the pull request is from a fork by comparing repository details and added corresponding logging for clarity.
* Updated the branch deletion logic to skip deletion for branches from forks, along with appropriate logging messages.
=> feat: enhance PR merge logic to skip branch deletion for forked PRs

src/data/events.json
feat : add new SRE event on July5th
=> feat : add new SRE event on July5th

src/data/communities.json, src/data/events.json
Added GDG Cloud Chennai Community to the communities list and updated time of the GCCD event.
=> feat: add GDG Cloud Chennai to community page

src/data/events.json
added details about upcoming typecoders meetup , by mistake i edited the gdg community logo. sorry for that guys
=> typedcoders tech meetup details added by Syed

src/data/events.json
We here at Global AI Coimbatore have organised an event that dives into the world of automation with N8N, making it fun along the way by indulging participants into group activities. The event is scheduled to take place on 26th July at Thoughtworks Technologies (India) Pvt Ltd
, KCT Tech Park, 1st Floor, Thudiyalur Rd, Saravanampatti · Coimbatore. Open for anyone willing to learn about AI!
=> feat: add N8N & AI Automation: Real Systems for Professionals - Azure AI Platform on 2025-07-26

src/data/events.json
Just a little update in the image url
=> fix: updated image url

src/components/pages/Communities/Community.tsx, src/components/pages/Communities/HoverIcon.tsx, src/data/communities.json
- Minimum height for community description
> Before
> After
- The hover color not working except for Linkedin since it was the first one, Tailwind does not support dynamic class insertion but does when the component re-renders hence fixed it accordingly
> Before
> After
- There's no color called `text-pink-600` supported by tw hence used `text-pink-500` for instagram
- Some communities have reddit pages listed like Django India, hence gave a support for Reddit URLs
=> feat: 22 community details with description

package-lock.json, src/components/pages/Archive/archive.tsx
Added filter and sort functionalities in the archive page. Closes #353
=> feat: added filter and sort functionlities in archives page

src/data/events.json
Added entry for - from dev to ops -  Community event on aug 9
=> feat: add from dev to ops event on aug 9

src/data/events.json
Reverts FOSSUChennai/Communities#378
=> Revert "feat: add from dev to ops event on aug 9"

src/data/events.json
Address and Registration link updated
=> fix: updated address and registration link in events.json

src/data/events.json
- Add JSLovers Chennai 1st anniversary meetup to tamilnadu tech
=> feat: add JSLovers meetup on September 13th

package-lock.json, src/components/shared/footer.tsx
Added a new link to the footer 
Fixes #355
=> Added wiki.tamilnadu.tech to the footer

src/components/PushSubscribe.tsx
Hi Team, This PR enhances the notification behavior by introducing timed display functionality.
- The notification will automatically pop up **after 5 seconds once the page loads**.  
- It will remain visible for **10 seconds** once it appears and will then dismiss automatically.  
https://github.com/user-attachments/assets/d2946535-b1b3-4e7b-aa5f-a97c89385476
Closes #410
=> To add timed notification with delayed display and auto-hide

src/data/communities.json, src/data/events.json
Added Digital Dreamers Den (D3) Meetup 5 on 2025-11-22
=> feat: add Digital Dreamers Den (D3) Meetup #5 on 2025-11-22

src/data/events.json
Adding new AI Geeks event in Chennai
=> feat: AI Geeks Chennai meetup

src/data/events.json
=> feat: Adding AI Geeks meetup

src/data/events.json
As mentioned in previous PR, i resolved the conflicts and attached a working ss.
=> feat: add codesapiens-meetup on 2025-10-11
